name: Package and release

on:
  push:
    tags:
      - '**'

jobs:

  release:

    runs-on: ubuntu-latest

    env:
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
      WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}

    steps:

      - name: Clone project
        uses: actions/checkout@v2
        with:
          fetch-depth: 5

      - name: WoW Packager
        uses:  BigWigsMods/packager@v2.0.3
        with:
          args: -p 963302